Introduce + element
awesome-academy/clean-code-swift pull request #2
Opened 2021-10-21 08:00 UTC by namtn-2711

Introduce + element

2021-10-21 09:00 UTC, tuanlvt-1117 approved these changes

2021-10-22 03:48 UTC, vietnh-1109 approved these changes

2021-10-22 05:50 UTC, tuannm-1276 approved these changes

2021-10-22 09:30 UTC, daolq-2712 requested changes
Pls check my comment!

2021-10-22 09:30 UTC, daolq-2712 commented on README.md
> +you shout when reading code](http://www.osnews.com/images/comics/wtfm.jpg)
```suggestion
you shout when reading code](http://www.osnews.com/images/comics/wtfm.jpg)

```

2021-10-22 09:30 UTC, daolq-2712 commented on README.md
> +Tường minh thì tốt hơn là ẩn.
```suggestion
Tường minh thì tốt hơn là ẩn.

```

2021-10-25 00:58 UTC, daolq-2712 approved these changes
LGTM!

2021-10-25 00:58 UTC, merged